name: Continous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-windows-and-clang-versions:
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-2022
        clang-version:
          - 17.0.6
          - 18.1.0
          - 18.1.1
          - 18.1.2
          - 18.1.4
          - 18.1.5
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up C++ environment
        uses: aminya/setup-cpp@v1
        with:
          compiler: clang-${{ matrix.clang-version }}
          clangtidy: ${{ matrix.clang-version }}
          clangformat: ${{ matrix.clang-version }}
